name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Read Cargo.toml
        id: crate
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Cargo.toml
      - name: Echo Cargo.toml
        run: echo ${{ steps.crate.outputs.content }}
